apiVersion: batch.schwarzeni.github.com/v1alpha1
kind: AppService
metadata:
  name: usercenter
spec:
  gateway_register_info:
    feature_enabled: true
    register_url: controller
    port: 80
    service_path: "/usercenter"

  replicas: 1
  image: appropriate/curl:latest
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

